@startuml 用例图

actor 总管理员 as adm
actor 问卷填写者

问卷填写者 -down-> (下载样例表)
问卷填写者 -down-> (上传填写后的表)
问卷填写者 -down-> (查看填写结果)
问卷填写者 -left-> (修改密码)

adm -> (管理公司列表)
(管理公司列表) <|- (增|删|改)
(管理公司列表) <|- (查)
(管理公司列表) <|- (查看已填写未填写)
(查看已填写未填写) ..> (查) : extend


@enduml